name: hadigro_organizer
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  get_it: ^7.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  qr_code_scanner: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/images/

 